### ISSUE TITLE
Animate task

### ISSUE THREAD

**Issue by DarkMatters** [VarynInc/game-experiments#1]
animate the airplane to a specified target on the canvas.

1. code will go in `stagemouseup` event (`handleMouseUp`), when the user releases the mouse button click, but put the code in a separate function and call it from there.
2. rotate the airplane such that is it facing the point the user clicked/mouse-upped
3. animate the airplane to that point

**Comment by varyndev** [comment]
A few updates to this PR:

1. Move code that computes the angle into a function.

```javascript
let angle = calcAngleDegrees(sprite.x, sprite.y, mouse.x, mouse.y)
```

parameters are the x and y positions of any 2 points, and returns the angle in degrees for the first object to face the second object. Note that this function accepts positions for 2 objects, meaning that we can reuse it for calculating the angle between any 2 objects.

2. Change the registration of the sprite to its center. This will improve the rotation about the sprite center point instead of 0,0.

```javascript
        airplane = new createjs.Bitmap(loader.getResult("airplane"));
        airplane.y = stageHeight * 0.5;
        airplane.x = stageWidth * 0.5;
        airplane.regX = airplane.image.width * 0.5;
        airplane.regY = airplane.image.height * 0.5;
        stage.addChild(airplane);
```

3. move the sprite/bitmap creation code into its own function. The function should take a parameter indicating which sprite we want created and which parent we want the sprite added to. Then we can reuse this function to create multiple sprites on demand as the game progresses.

```javascript
function createAirplaneSprite(assetName, parent) {
        let airplane = new createjs.Bitmap(loader.getResult(assetName));
        airplane.y = stageHeight * 0.5;
        airplane.x = stageWidth * 0.5;
        airplane.regX = airplane.image.width * 0.5;
        airplane.regY = airplane.image.height * 0.5;
        parent.addChild(airplane);
        return airplane;
}
```

**Comment by varyndev** [comment]
See issue #6

**Comment by varyndev** [comment]
Completed in #6
